### ISSUE TITLE
Issues with deploy.sh giving error stat \: no such file or directory in pipeline bitbucket

### ISSUE THREAD

**Issue by Stvdputten** [bootstrapping-microservices/chapter-9#14]
During the pipeline on bitbucket I kept getting an error. It might be because of the extra \ at the final line of code. After removing this I got it working. So I would recommend changing the code.
```diff
-     -var "storage_access_key=$STORAGE_ACCESS_KEY"  \ 
+    -var "storage_access_key=$STORAGE_ACCESS_KEY"  
```

**Comment by ashleydavis** [comment]
Thanks so much for reporting the issue! I've updated the code accordingly.
