### ISSUE TITLE
Test can't pass

### ISSUE THREAD

**Issue by BobJackson** [bootstrapping-microservices/chapter-9#15]
## It's quite strange! Why it can't load "http://localhost:4000/", I can open this link in my chrome independently.
![image](https://user-images.githubusercontent.com/15266708/112262492-b391c000-8ca8-11eb-8d2f-ca2344c1d329.png)

![image](https://user-images.githubusercontent.com/15266708/112262748-197e4780-8ca9-11eb-8ec6-f3141f22f1c7.png)

**Comment by ashleydavis** [comment]
That's strange.

I'm going to be using the chapter 9 example in a demonstration soon, so I'll grab a fresh copy and run it myself and let you know if I find and fix any issues.

In the meantime if you come across a solution to the problem please let me know and I'll update the code.

**Comment by ashleydavis** [comment]
As far I can tell the ch-9 code example is working ok.

Are you able to give me more details about how you are running it and what (if any) errors you are seeing?

**Comment by ashleydavis** [comment]
Closed due to inactivity.
