### ISSUE TITLE
"Error Saving Credentials" on docker login in main.tf

### ISSUE THREAD

**Issue by jordac67** [bootstrapping-microservices/chapter-9#24]
I keep running into this error whenever i run `terraform apply`, it repeats this error for every service except `video-streaming` which successfully builds first. It seems it only completes this script for that service and throws this error on the rest. Sadly I am not familiar enough with how docker is saving the credentials to bypass this issue. 

<img width="1172" alt="Screen Shot 2021-08-19 at 12 50 16 AM" src="https://user-images.githubusercontent.com/13411923/130030390-90039e41-14a2-4250-b156-5ad78d178928.png">

**Comment by ashleydavis** [comment]
Can you run `docker login` successfully outside Terraform?

What platform are you on?

**Comment by ashleydavis** [comment]
What operating system are you running it on?

Can you run `docker login` directly from the command line? You should try it without `terraform` to check that that your username and password for the container registry work.

**Comment by jordac67** [comment]
> What operating system are you running it on? (If you tell me I'll can try running it on that OS to see what happens).

Yup, my OS is macOS Big Sur version 11.5.2 

> Can you run docker login directly from the command line? You should try it without terraform to check that that your username and password for the container registry work.

Yup I verified that this is working correctly.

**Comment by jordac67** [comment]
I'm just going to close this issue, my workaround was to just remove the repeated login step for every service. Still haven't been able to find out why it was giving me that error.

**Comment by ashleydavis** [comment]
Hi @jordac67 thanks for letting me know. If you get any more understanding of the problem please add more here. 

Thank you
